name: Go
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: set env
        run: |
          echo "OAUTH_CLIENT_ID=${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}" >> $GITHUB_ENV
          echo "OAUTH_CLIENT_SECRET=${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}" >> $GITHUB_ENV
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.14'
          check-latest: true
      - run: go run main.go      