
on:
  push:
    branches:
      - PE-test
      
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github variables
        id: get_ref
        run: |
          output_file="final_result"
          echo "brokers-dmx-prod-non-revenue-eks-2.kafka-us-east-1b.vungle.io 66" >> final_result
          echo "brokers-dmx-prod-non-revenue-eks-3.kafka-us-east-1b.vungle.io 78" >> final_result
          
          cat final_result
          
          file_content=""
          while read -r line; do
            file_content+="$line"$'\n'  # Append line and add a newline character
            echo "$line" >> $GITHUB_OUTPUT
          done < final_result
          
          echo $file_content
          
          
      # To be continue for run ANsible script  
      - name: Run Ansible playbook
        run: |
          echo "${{ steps.get_ref.outputs.* }}"
       